// <auto-generated />
using System;
using BudgetTracker.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTracker.Domain.Migrations
{
    [DbContext(typeof(BudgetTrackerDbContext))]
    [Migration("20260604020518_AddPlaidIntegration")]
    partial class AddPlaidIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Accounts_User_Name");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NetIncomeMonthly")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("PlanMonth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlanMonth", "IsActive")
                        .HasDatabaseName("IX_BudgetPlans_User_Month_Active");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "PlanMonth", "IsActive"), new[] { "Name", "NetIncomeMonthly" });

                    b.HasIndex("UserId", "PlanMonth", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_BudgetPlans_User_Month_Name");

                    b.ToTable("BudgetPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPlans_NetIncome", "NetIncomeMonthly >= 0");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlanEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BudgetPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsStressFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MonthlyEquivalent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetPlanId", "Bucket", "LineType")
                        .HasDatabaseName("IX_BudgetPlanEntries_Plan_Bucket_Type");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("BudgetPlanId", "Bucket", "LineType"), new[] { "MonthlyEquivalent", "Amount", "Cadence", "CategoryId", "SortOrder" });

                    b.ToTable("BudgetPlanEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPlanEntries_Amount", "Amount >= 0");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_Bucket", "Bucket IN ('Core', 'Buffer')");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_Cadence", "Cadence IN ('Monthly', 'Annual')");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_LineType", "LineType IN ('Income', 'Expense')");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_MonthlyEq", "MonthlyEquivalent >= 0");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Expense");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_User_Name");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_CategoryType", "CategoryType IN ('Expense', 'Income', 'Both')");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountSubtype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mask")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlaidItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaidAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlaidAccounts_PlaidAccountId");

                    b.HasIndex("PlaidItemId");

                    b.ToTable("PlaidAccounts", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ConsentExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaidItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SyncCursor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaidItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlaidItems_PlaidItemId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlaidItems_UserId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("PlaidItems", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payee")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlaidAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlaidTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransferAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Transactions_PlaidTransactionId")
                        .HasFilter("[PlaidTransactionId] IS NOT NULL");

                    b.HasIndex("TransferAccountId");

                    b.HasIndex("AccountId", "OccurredAt")
                        .HasDatabaseName("IX_Transactions_AccountId_OccurredAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AccountId", "OccurredAt"), new[] { "TransactionType", "Amount", "CategoryId" });

                    b.HasIndex("CategoryId", "OccurredAt")
                        .HasDatabaseName("IX_Transactions_CategoryId_OccurredAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "OccurredAt"), new[] { "TransactionType", "Amount", "AccountId" });

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_NonZeroAmount", "Amount <> 0");

                            t.HasCheckConstraint("CK_Transactions_TransactionType", "TransactionType IN ('Expense', 'Income', 'Transfer', 'Adjustment')");

                            t.HasCheckConstraint("CK_Transactions_TransferAccount", "(TransactionType = 'Transfer' AND TransferAccountId IS NOT NULL) OR (TransactionType <> 'Transfer' AND TransferAccountId IS NULL)");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CognitoSub")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CognitoSub")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_CognitoSub")
                        .HasFilter("[CognitoSub] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Account", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlan", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlanEntry", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.BudgetPlan", "BudgetPlan")
                        .WithMany("Entries")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Domain.Models.Category", "Category")
                        .WithMany("BudgetPlanEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BudgetPlan");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Category", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidAccount", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.PlaidItem", "Item")
                        .WithMany("Accounts")
                        .HasForeignKey("PlaidItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidItem", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Domain.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BudgetTracker.Domain.Models.Account", "TransferAccount")
                        .WithMany()
                        .HasForeignKey("TransferAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransferAccount");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Category", b =>
                {
                    b.Navigation("BudgetPlanEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidItem", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BudgetPlans");

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
