// <auto-generated />
using System;
using BudgetTracker.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Domain.Migrations
{
    [DbContext(typeof(BudgetTrackerDbContext))]
    partial class BudgetTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Accounts_UserId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("NetIncomeMonthly")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PlanMonth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlanMonth", "IsActive")
                        .HasDatabaseName("IX_BudgetPlans_User_Month_Active");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "PlanMonth", "IsActive"), new[] { "Name", "NetIncomeMonthly" });

                    b.ToTable("BudgetPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPlans_NetIncome", "\"NetIncomeMonthly\" >= 0");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlanEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("BudgetPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc')");

                    b.Property<bool>("IsStressFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("MonthlyEquivalent")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetPlanId", "Bucket", "LineType")
                        .HasDatabaseName("IX_BudgetPlanEntries_Plan_Bucket_Type");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("BudgetPlanId", "Bucket", "LineType"), new[] { "MonthlyEquivalent", "Amount", "Cadence", "CategoryId", "SortOrder" });

                    b.ToTable("BudgetPlanEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPlanEntries_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_Bucket", "\"Bucket\" IN ('Core', 'Buffer')");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_Cadence", "\"Cadence\" IN ('Monthly', 'Annual')");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_LineType", "\"LineType\" IN ('Income', 'Expense')");

                            t.HasCheckConstraint("CK_BudgetPlanEntries_MonthlyEq", "\"MonthlyEquivalent\" >= 0");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Expense");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlaidCategoryPrimary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Categories_UserId");

                    b.HasIndex("UserId", "PlaidCategoryPrimary")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_User_PlaidCategory")
                        .HasFilter("\"PlaidCategoryPrimary\" IS NOT NULL");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_CategoryType", "\"CategoryType\" IN ('Expense', 'Income', 'Both')");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountSubtype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mask")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PlaidItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlaidAccountId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlaidAccounts_PlaidAccountId");

                    b.HasIndex("PlaidItemId");

                    b.ToTable("PlaidAccounts", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ConsentExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc')");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PlaidItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SyncCursor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlaidItemId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlaidItems_PlaidItemId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PlaidItems_UserId");

                    b.ToTable("PlaidItems", (string)null);
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc')");

                    b.Property<bool>("IsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Payee")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PlaidAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlaidCategoryPrimary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlaidTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TransferAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Transactions_PlaidTransactionId")
                        .HasFilter("\"PlaidTransactionId\" IS NOT NULL");

                    b.HasIndex("TransferAccountId");

                    b.HasIndex("AccountId", "OccurredAt")
                        .HasDatabaseName("IX_Transactions_AccountId_OccurredAt");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AccountId", "OccurredAt"), new[] { "TransactionType", "Amount", "CategoryId" });

                    b.HasIndex("CategoryId", "OccurredAt")
                        .HasDatabaseName("IX_Transactions_CategoryId_OccurredAt");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "OccurredAt"), new[] { "TransactionType", "Amount", "AccountId" });

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_NonZeroAmount", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_Transactions_TransactionType", "\"TransactionType\" IN ('Expense', 'Income', 'Transfer', 'Adjustment')");

                            t.HasCheckConstraint("CK_Transactions_TransferAccount", "(\"TransactionType\" = 'Transfer' AND \"TransferAccountId\" IS NOT NULL) OR (\"TransactionType\" <> 'Transfer' AND \"TransferAccountId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CognitoSub")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("CognitoSub")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_CognitoSub")
                        .HasFilter("\"CognitoSub\" IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Account", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlan", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlanEntry", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.BudgetPlan", "BudgetPlan")
                        .WithMany("Entries")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Domain.Models.Category", "Category")
                        .WithMany("BudgetPlanEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BudgetPlan");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Category", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidAccount", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.PlaidItem", "Item")
                        .WithMany("Accounts")
                        .HasForeignKey("PlaidItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidItem", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Domain.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Domain.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BudgetTracker.Domain.Models.Account", "TransferAccount")
                        .WithMany()
                        .HasForeignKey("TransferAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransferAccount");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.BudgetPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.Category", b =>
                {
                    b.Navigation("BudgetPlanEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.PlaidItem", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BudgetTracker.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BudgetPlans");

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
